### ISSUE TITLE
Announcements doesnt show up

### ISSUE THREAD

**Issue by H-Sundberg** [Grupp-17/canvas-discord-bot#5]
**Environment**
_Where did the bug occure? (Discord, database, in the code)_

Operating system: Microsoft Windows 10 Home
Version: 10.0.19042 version 19042
Code editor: Visual Studio Code (version?) through subsystem: WSL, Ubuntu
Branch: testing
Commit-ID: f67a5f129b9e45d039655de3b02bf07b9140ef52
File and database: canvas-discord-bot/database > sqlite3 > main.db
Version of Discord: which version? (for users or testversion?)

**Steps to reproduce**
_How do we reproduce the test to get the same bug?_

canvas > courses > "Programmera en bot" > add new announcement > publish/save

This is depending on the lenght of the announcement or if the announcement contains copied text

**Expected Result**
_What output was expected?_

Expected output that the announcement shows up at the discord channel and in the database. 

**Actual Result**
_What output did I get?_

Some announcements doesnt show up either on discord or in database. The bug was noticed first with the announcement “Programmeringsläxan”, which contains copied text of "Lipsum" text, 176 words.

**Visual Proof**
_Screenshots, videos or text_
img 1:
![image](https://user-images.githubusercontent.com/77834886/116674748-5246c600-a9a5-11eb-8334-e12059b9b437.png)
img 2:
![image](https://user-images.githubusercontent.com/77834886/117464953-754b1a00-af51-11eb-94f8-0a1c164e21ba.png)
img 3:
![image](https://user-images.githubusercontent.com/77834886/117466049-98c29480-af52-11eb-9728-c1f6ecececee.png)
img 4:
![image](https://user-images.githubusercontent.com/77834886/117467408-f2778e80-af53-11eb-99de-60fa9d5e57c1.png)
img 5:
![image](https://user-images.githubusercontent.com/77834886/117468169-b42e9f00-af54-11eb-94c1-782d46b611e2.png)
img 6:
![image](https://user-images.githubusercontent.com/77834886/117547744-92efb080-b031-11eb-8a61-e8b422ce3778.png)
img 7:
![image](https://user-images.githubusercontent.com/77834886/117547894-53759400-b032-11eb-9cb1-47333122773f.png)
 img 8:
![image](https://user-images.githubusercontent.com/77834886/117547931-7acc6100-b032-11eb-9afb-c9a412d44ffd.png)
img 9:
![image](https://user-images.githubusercontent.com/77834886/117548398-1959c180-b035-11eb-86c4-35368dbe9ba6.png)

**Allready tested**

Announcements does not show up on Discord or in database when testing following:

T1 - 2 - Reproducing new announcment containing exact same message as "Programmeringsläxan", but with different title
Copied text from some web page, longer message
T1 - 9 - Copied text from gu canvas, longer message (146 words)
 T1 - 10 - Copied text from github, shorter message (4 words)
T1 - 13 - Reproducing new announcment containing exact same message as "Programmeringsläxan", but in different course (ORG311)
T1 - 18 - Reproducing new announcment containing exact same message as "Programmeringsläxan", but in different course (GRK102)
T1 - 20 - copied text
T1 - 21 - copied text

Announcements does not show up on Discord but in database when testing following:

Dubbeltest av T1 - 12 - Duplicate of Heidis self written story to secure different environment doesnt affect this test (copied  the text from canvas T1 - 12, img 3 under visual proof)
T1 - 22 - copied text
T1 - 23 - self written text
T1 - 24 - duplicated, same message as "Programmeringsläxan", (to see if it shows up "occasionally")

Announcements show up on Discord and in database when testing following:

T1 - 6 - Symbols, like @£$€
T1 - 5 - The letters "ÅÄÖ"
T1 - 4 -  Longer messages Space/gap in text, between pieces of text
T1 - 3 - Shorter messages
T1 - 11 - Copied text from web page, middle lenght of message, 36 words (text from codeinstitute)
T1 - 7 - Test with the same lenght of "Programmeringsläxan", but with the same words duplicated over and over again (176 words)
T1 - 12 - Test with 176 self-written words (not copied from web page and not duplicated from previouse text like: "test med 176 ord, test med 176 ord...." 
T1 - 14 - test with self written words in different course (ORG311)
T1 - 15 - Test with the same lenght of "Programmeringsläxan", but with the same words duplicated over and over again (176 words), but in different course (ORG311)
T1 - 16 - test with self written words in different course (GRK102)
T1 - 17 - Test with the same lenght of "Programmeringsläxan", but with the same words duplicated over and over again (176 words), but in different course (GRK102)
T1 - 19 -  digits

Thoughts this far:
Seems like it depends on where the text is copied from. Perhaps it's also depending on the lenght of text in the announcement.

**Test after first try to fix:**

Branch: testing
commit-ID: 6b965017461a8ccb7253f0cbe08cc310714cec74

Announcements show up on Discord and in database when testing following:

Announcements does not show up on Discord but in database when testing following:
T1 - 25 - Longer message (287 words)
T1 - 27 - Copied text from codeinstitute (52 words)
T1 - 28 - self written text (18 words)

Announcements does not show up on Discord or in database when testing following:
T1 - 26 - copied text, same as "Programmeringsläxan"

test resulted in exception error in vs code terminal (img 6 under visual proof)

When I tried to enter database main.db I got the message "Database is locked" (img 7 under visual proof), but after trying a second time it worked (img 8). T1-25 shows up in database, but not T1-26 or T1-27.

branch: main
commit-ID: 0f590e3a6659279e9aeab59852a9af31bac1e068

Announcements does not show up on Discord but in database when testing following:
T1 - 29 - Longer message (287 words)
T1 - 31 - Copied text from codeinstitute (52 words)
T1 - 32 - self written text (18 words)

(img 9 under visual proof)

Announcements does not show up on Discord or in database when testing following:
T1 - 30 - copied text, same as "Programmeringsläxan"

**Severity/Priority**
_Does this needs to be fixed urgently? How urgent?_

Quite urgent, important that all announcements shows up independently of content or lenght.

**Comment by heidihdmn** [comment]
Add: what commit id (version) the bug appeared in and in what branch 
😄

**Comment by H-Sundberg** [comment]
Test result after ad hoc solution: Still an issue. Tested in both testing branch and main branch. @Tove-A @Dedas

**Comment by H-Sundberg** [comment]
Issue tesed and bug is solved, parameterized queries was the sulotion
